#!/usr/bin/env bash
# =============================================================================
# gen-compose-override.sh
#
# Generates docker-compose.override.yml for multi-runner scaling.
# Called automatically by restore.sh; can also be run manually.
#
# Reads from .env (or environment):
#   RUNNER_REPLICAS    - number of runner containers (default: 1)
#   RUNNER_CONCURRENCY - Xvfb displays per runner   (default: 4)
#
# When RUNNER_REPLICAS=1:
#   - Writes an empty override (no extra services, no nginx upstream)
#   - RUNNER_URL stays as http://qaasr-runner:5001 (direct)
#
# When RUNNER_REPLICAS>1:
#   - Creates qaasr-runner-1, qaasr-runner-2, ... qaasr-runner-N
#   - Adds nginx upstream block (runner-lb.conf) with least_conn
#   - Sets RUNNER_URL=http://qaasr-nginx/runner-lb in the override
#   - Writes nginx/runner-lb.conf used by the nginx container
# =============================================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Load .env if present ──────────────────────────────────────────────────────
if [[ -f ".env" ]]; then
  set -o allexport
  # shellcheck disable=SC1091
  source <(grep -E '^[A-Z_]+=.*' .env | grep -v '^#')
  set +o allexport
fi

RUNNER_REPLICAS="${RUNNER_REPLICAS:-1}"
RUNNER_CONCURRENCY="${RUNNER_CONCURRENCY:-4}"
OUT="docker-compose.override.yml"
NGINX_LB_CONF="nginx/runner-lb.conf"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info() { echo -e "${CYAN}  [gen-override]${NC}  $*"; }
ok()   { echo -e "${GREEN}  [gen-override]${NC}  $*"; }

# ── Single replica — write empty override, nothing to do ─────────────────────
if [[ "$RUNNER_REPLICAS" -le 1 ]]; then
  cat > "$OUT" <<'EOF'
# Auto-generated by gen-compose-override.sh (RUNNER_REPLICAS=1)
# No extra runner services needed. API talks directly to qaasr-runner:5001.
EOF
  # Remove LB conf if it exists from a previous multi-replica run
  rm -f "$NGINX_LB_CONF"
  ok "RUNNER_REPLICAS=1 -- single runner, no override needed"
  exit 0
fi

# ── Multi-replica — build override ───────────────────────────────────────────
info "Generating override for RUNNER_REPLICAS=$RUNNER_REPLICAS, RUNNER_CONCURRENCY=$RUNNER_CONCURRENCY"

# Collect all runner service names for nginx upstream
UPSTREAM_SERVERS=""
for i in $(seq 1 "$RUNNER_REPLICAS"); do
  UPSTREAM_SERVERS="${UPSTREAM_SERVERS}        server qaasr-runner-${i}:5001;\n"
done

# ── Write nginx/runner-lb.conf ────────────────────────────────────────────────
mkdir -p nginx
cat > "$NGINX_LB_CONF" <<EOF
# Auto-generated by gen-compose-override.sh -- DO NOT EDIT MANUALLY
# Included by nginx.conf when RUNNER_REPLICAS > 1.
upstream qaasr_runners {
    least_conn;
$(printf '%b' "$UPSTREAM_SERVERS")}

server {
    listen 8081;

    # /runner-lb proxies to the upstream runner pool.
    # The API sends POST /run here; nginx routes to the least-loaded runner.
    # proxy_buffering off is critical -- runner responses are NDJSON streams.
    location / {
        proxy_pass         http://qaasr_runners;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   Connection        "";
        proxy_buffering    off;
        proxy_read_timeout 1200s;
        proxy_send_timeout 1200s;
        client_max_body_size 50m;
    }
}
EOF
ok "nginx/runner-lb.conf written ($RUNNER_REPLICAS upstream servers)"

# ── Build the services block ─────────────────────────────────────────────────
SERVICES_BLOCK=""
for i in $(seq 1 "$RUNNER_REPLICAS"); do
  SERVICES_BLOCK="${SERVICES_BLOCK}
  qaasr-runner-${i}:
    extends:
      file: docker-compose.yml
      service: qaasr-runner
    container_name: qaasr-runner-${i}
    ports:
      - \"127.0.0.1:$((6079 + i)):6080\"
"
done

# ── Write docker-compose.override.yml ────────────────────────────────────────
cat > "$OUT" <<EOF
# Auto-generated by gen-compose-override.sh
# RUNNER_REPLICAS=${RUNNER_REPLICAS}  RUNNER_CONCURRENCY=${RUNNER_CONCURRENCY}
# Total parallel slots: $((RUNNER_REPLICAS * RUNNER_CONCURRENCY))
# DO NOT EDIT MANUALLY -- re-run gen-compose-override.sh to regenerate.

name: qa-automation-suite-runner

services:

  # ── Disable the base single runner when using replicas ───────────────────
  qaasr-runner:
    profiles: [disabled]

  # ── Runner replicas ──────────────────────────────────────────────────────
$(printf '%s' "$SERVICES_BLOCK")
  # ── API: point RUNNER_URL at nginx runner-lb ─────────────────────────────
  qaasr-api:
    environment:
      - RUNNER_URL=http://qaasr-nginx:8081
      - RUNNER_PRIMARY_URL=http://qaasr-nginx:8081

  # ── Nginx: mount runner-lb.conf ──────────────────────────────────────────
  qaasr-nginx:
    volumes:
      - ./nginx/runner-lb.conf:/etc/nginx/conf.d/runner-lb.conf:ro
EOF

TOTAL=$((RUNNER_REPLICAS * RUNNER_CONCURRENCY))
ok "docker-compose.override.yml written"
ok "  Runners : qaasr-runner-1 .. qaasr-runner-${RUNNER_REPLICAS}"
ok "  Slots   : ${RUNNER_CONCURRENCY} per runner x ${RUNNER_REPLICAS} replicas = ${TOTAL} total"
ok "  noVNC   : ports $((6079 + 1))-$((6079 + RUNNER_REPLICAS)) (runner-1 to runner-${RUNNER_REPLICAS})"
echo ""
echo "  Run:  docker compose up -d"
