#!/usr/bin/env bash
# =============================================================================
# gen-compose-override.sh
#
# Generates docker-compose.override.yml for multi-runner scaling.
# Called automatically by restore.sh; can also be run manually.
#
# Reads from .env (or environment):
#   RUNNER_REPLICAS    - number of runner containers (default: 1)
#   RUNNER_CONCURRENCY - Xvfb displays per runner   (default: 4)
#
# When RUNNER_REPLICAS=1:
#   - Writes an empty override (no changes, single qaasr-runner as usual)
#
# When RUNNER_REPLICAS>1:
#   - Creates qaasr-runner-1, qaasr-runner-2, ... qaasr-runner-N
#   - Disables the base qaasr-runner service
#   - The API round-robins across runner URLs directly (no nginx LB needed)
#   - noVNC ports: runner-1 on 6080, runner-2 on 6081, runner-N on 6079+N
# =============================================================================

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Load only the two scaling vars from .env (avoids sourcing unsafe values) ──
if [[ -f ".env" ]]; then
  _r=$(grep -E '^RUNNER_REPLICAS=' .env | tail -1 | cut -d= -f2 | tr -d '"' | tr -d "'")
  _c=$(grep -E '^RUNNER_CONCURRENCY=' .env | tail -1 | cut -d= -f2 | tr -d '"' | tr -d "'")
  [[ -n "$_r" ]] && RUNNER_REPLICAS="$_r"
  [[ -n "$_c" ]] && RUNNER_CONCURRENCY="$_c"
fi

RUNNER_REPLICAS="${RUNNER_REPLICAS:-1}"
RUNNER_CONCURRENCY="${RUNNER_CONCURRENCY:-4}"
OUT="docker-compose.override.yml"

RED='\033[0;31m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'
info() { echo -e "${CYAN}  [gen-override]${NC}  $*"; }
ok()   { echo -e "${GREEN}  [gen-override]${NC}  $*"; }

# ── Single replica — write empty override, nothing to do ─────────────────────
if [[ "$RUNNER_REPLICAS" -le 1 ]]; then
  cat > "$OUT" <<'EOF'
# Auto-generated by gen-compose-override.sh (RUNNER_REPLICAS=1)
# Single runner mode -- no extra services needed.
# API calls http://qaasr-runner:5001 directly.
EOF
  ok "RUNNER_REPLICAS=1 -- single runner, no override needed"
  exit 0
fi

# ── Multi-replica — build runner services ────────────────────────────────────
info "Generating override for RUNNER_REPLICAS=$RUNNER_REPLICAS, RUNNER_CONCURRENCY=$RUNNER_CONCURRENCY"

SERVICES_BLOCK=""
for i in $(seq 1 "$RUNNER_REPLICAS"); do
  NOVNC_HOST_PORT=$((6079 + i))
  SERVICES_BLOCK="${SERVICES_BLOCK}
  qaasr-runner-${i}:
    image: qaasr-runner:latest
    container_name: qaasr-runner-${i}
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - API_URL=http://qaasr-api:4000
      - SE_AVOID_STATS=true
      - RUNNER_CONCURRENCY=${RUNNER_CONCURRENCY}
    depends_on:
      qaasr-api:
        condition: service_healthy
    ports:
      - \"127.0.0.1:${NOVNC_HOST_PORT}:6080\"
    volumes:
      - qaasr-scripts:/scripts
      - qaasr-artifacts:/artifacts
    shm_size: '512m'
    healthcheck:
      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:5001/health\"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 3g
        reservations:
          memory: 512m
    networks:
      - qaasr-net
"
done

TOTAL=$((RUNNER_REPLICAS * RUNNER_CONCURRENCY))

cat > "$OUT" <<EOF
# Auto-generated by gen-compose-override.sh
# RUNNER_REPLICAS=${RUNNER_REPLICAS}  RUNNER_CONCURRENCY=${RUNNER_CONCURRENCY}
# Total parallel slots: ${TOTAL}
# DO NOT EDIT MANUALLY -- re-run gen-compose-override.sh to regenerate.
#
# Routing: API round-robins directly across runner URLs (no nginx LB).
# Runner URLs: http://qaasr-runner-1:5001 .. http://qaasr-runner-${RUNNER_REPLICAS}:5001

name: qa-automation-suite-runner

services:

  # ── Disable the base single-runner when using replicas ───────────────────
  qaasr-runner:
    profiles: [disabled]

  # ── Runner replicas (API dispatches to these directly, round-robin) ──────
$(printf '%s' "$SERVICES_BLOCK")
EOF

ok "docker-compose.override.yml written"
ok "  Runners : qaasr-runner-1 .. qaasr-runner-${RUNNER_REPLICAS}"
ok "  Slots   : ${RUNNER_CONCURRENCY} per runner x ${RUNNER_REPLICAS} = ${TOTAL} total parallel runs"
ok "  noVNC   : ports $((6079 + 1))-$((6079 + RUNNER_REPLICAS)) on host"
echo ""
echo "  Run:  docker compose up -d"
